import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lab 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lab 2022 Facebook Like Website</h1>
    </div>
  )
}
